// <auto-generated />
using System;
using Alfreelina_P2_AP1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alfreelina_P2_AP1.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Alfreelina_P2_AP1.Entidades.ProyectoDetalle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("TareaID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tiempo")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("ProyectoID");

                    b.HasIndex("TareaID");

                    b.ToTable("ProyectoDetalle");
                });

            modelBuilder.Entity("Alfreelina_P2_AP1.Entidades.Proyectos", b =>
                {
                    b.Property<int>("ProyectoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("TiempoTotal")
                        .HasColumnType("REAL");

                    b.HasKey("ProyectoID");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Alfreelina_P2_AP1.Entidades.Tareas", b =>
                {
                    b.Property<int>("TareaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TareaID");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            TareaID = 1,
                            TipoTarea = "Diseño"
                        },
                        new
                        {
                            TareaID = 2,
                            TipoTarea = "Prueba"
                        },
                        new
                        {
                            TareaID = 3,
                            TipoTarea = "Analisis"
                        },
                        new
                        {
                            TareaID = 4,
                            TipoTarea = "Programacion"
                        });
                });

            modelBuilder.Entity("Alfreelina_P2_AP1.Entidades.ProyectoDetalle", b =>
                {
                    b.HasOne("Alfreelina_P2_AP1.Entidades.Proyectos", null)
                        .WithMany("ProyectoDetalle")
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alfreelina_P2_AP1.Entidades.Tareas", "tareas")
                        .WithMany()
                        .HasForeignKey("TareaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
